### PR TITLE
handling non-versioned pages in the versioned site arch - en

### LINKED ISSUE #940: Handling unversioned docs
Now that docs are organized by version, we do have some things that are not version-specific:

- Resources
- Design docs
- Contribute
- Troubleshooting
- FAQ

It will be nice to move these to the top level (same level as each release).
Alternatively they can be moved as links to the main homepage, but I'm afraid that might mean at least a minor re-design of the home page.

### PR DESCRIPTION
**Pull request by nate-double-u**
1. Handle non-versioned pages in the `en` versioned site architecture.
2. Create archive folder for older versions

The following folders have been moved out of individually versioned folders:
* troubleshoot
* faq
* design-doc(s)
* contributing

An archive folder has been created, and populated with 
* v11.0
* pdfs (removed from individually versioned folders)

fixes #940

## Draft
Things to consider
* [ ] `layouts/partials/docs/landing-page.htm` can be handled more elegantly
* [x] What to do with the Contribute, Design docs, troubleshoot, FAQs and Resources in v15?
   Contribute, Design docs, troubleshoot, FAQs and Resources were `git mv` from either v14 or v13 (resources weren't listed in every release), to help preserve git history. I didn't move anything from v15 as i wasn't sure if there were changes that would be lost
* [x] I've not moved any folders on the zh localizaton, but the way the layout file has been altered doesn't break the zh/docs landing page.

### CODE REVIEW

**Comment by nate-double-u** [comment]
deploy preview: https://deploy-preview-1085--vitess.netlify.app/docs/

**Comment by deepthi** [comment]
Initial feedback is that it maybe better to have the versioned docs listed first in the sidebar, and then the rest.

**Comment by deepthi** [comment]
Can we also move `Older Version Docs` to the unversioned section and rename it to `Docs Archive` OR `Archived docs`?

**Comment by nate-double-u** [comment]
> Can we also move `Older Version Docs` to the unversioned section and rename it to `Docs Archive` OR `Archived docs`?

We could do something like that. What versions should be in the archive?

**Comment by nate-double-u** [comment]
bump :)

**Comment by deepthi** [comment]
> > Can we also move `Older Version Docs` to the unversioned section and rename it to `Docs Archive` OR `Archived docs`?
> 
> We could do something like that. What versions should be in the archive?

I'd say v5.0 to v10.0 (both included). We can keep v11.0 (Archived) in the side bar for now. I'm also OK with moving the whole tree for v11.0 under Archived Docs.

**Comment by nate-double-u** [comment]
This latest commit adds an archive folder under the docs folder.

**Comment by nate-double-u** [comment]
https://deploy-preview-1085--vitess.netlify.app/docs/
https://deploy-preview-1085--vitess.netlify.app/docs/archive/
https://deploy-preview-1085--vitess.netlify.app/docs/archive/11.0/

**Comment by deepthi** [comment]
Some of the links under FAQ need to be fixed. They go to 14.0 or 13.0 docs instead of the unversioned versions.
It could be that they are full urls instead of relative paths
https://deploy-preview-1085--vitess.netlify.app/docs/faq/
- Contribute
- Pull Requests
- Issues
- Resources

> What to do with the Contribute, Design docs, troubleshoot, FAQs and Resources in v15?
Contribute, Design docs, troubleshoot, FAQs and Resources were git mv from either v14 or v13 (resources weren't listed in every release), to help preserve git history. I didn't move anything from v15 as i wasn't sure if there were changes that would be lost

Actually it would be better to mv them from v15 wherever possible and delete from v14 and prior. For Resources we probably need to move from v14 (or whatever the latest version is where they are present).
We might have made changes in v15 whereas v14 and prior have been essentially frozen.

**Comment by nate-double-u** [comment]
Given the size of this PR, i think I'd rather open a follow up issue to address the broken link fixes. Things will also be finalized, so we'll know for sure where to link stuff.

**Comment by thisisobate** [comment]
Looks good!
My only concern is that having older versions within v11.0 feels a bit out of place :stuck_out_tongue_closed_eyes: 
They should be listed in the side nav but under the archive section as you did with v11
Screenshot 2022-10-05 at 16 40 34

**Comment by nate-double-u** [comment]
> My only concern is that having older versions within v11.0 feels a bit out of place

I'm not sure what you mean. v11 is under the archive in the side bar, and there are no other versions I can see nested under v11.

>  They should be listed in the side nav but under the archive section as you did with v11

But no other versions are archived yet -- I think Vitess supports release + 2 versions and shares a beta (development), so v12-15 should all be active.

**Comment by thisisobate** [comment]
If you click the **older versioned docs** highlighted in the image below, it takes you to a page that lists versions/pdf from v5.0 to v12.0.
What I was saying was instead of having the **pdfs** file live under the v11 folder, it should live in the **archive** folder instead. So in the archive section in the navbar, we should have **v11.0** and **older versioned docs**.
Screenshot 2022-10-05 at 16 40 34

**Comment by nate-double-u** [comment]
> If you click the **older versioned docs** highlighted in the image below, it takes you to a page that lists versions/pdf from v5.0 to v12.0. What I was saying was instead of having the **pdfs** file live under the v11 folder, it should live in the **archive** folder instead. So in the archive section in the navbar, we should have **v11.0** and **older versioned docs**. 

I understand now! Thanks, and I agree, that's a little weird. I'll fix it 🙂

**Comment by nate-double-u** [comment]
v16.0 has been added -- I'll use it for the unversioned folders.

**Comment by nate-double-u** [comment]
I think that the links on the FAQ page are working. That said, when i run the link checker, there are a lot of broken links throughout the site. We should open a followup issue to address.

**Comment by nate-double-u** [comment]
The pdfs folders that were living under each version have been moved into the archive folder.

**Comment by deepthi** [comment]
Overall this is looking good. The only thing that would be better IMO is if we can move `Contribute` `Troubleshoot` and `FAQ` below `v12.0`.
@mattlord can your review this as well?

**Comment by thisisobate** [comment]
Looks good! My only observation is that **pdfs folder** is placed right before v11.0. I expect the reverse to be the case- `older versioned docs` should come last on the list.

Overall, great work! @nate-double-u

**Comment by mattlord** [comment]
We should update the Build pages to be more generic. For go and MySQL we can say "install the latest" and simply link to the install page for each. For example:
https://deploy-preview-1085--vitess.netlify.app/docs/contributing/build-on-centos/#install-dependencies
  - Go: https://go.dev/doc/install
  - MySQL: https://dev.mysql.com/doc/refman/en/installing.html

I can push a commit for this if you both like. We/I can also do it separately after this is merged.

Otherwise it looks good! THANK YOU ❤️

**Review by mattlord — APPROVED** [review]

**Comment by deepthi** [comment]
> We should update the Build pages to be more generic. For go and MySQL we can say "install the latest" and simply link to the install page for each. For example: https://deploy-preview-1085--vitess.netlify.app/docs/contributing/build-on-centos/#install-dependencies
> 

Oh yes, this is a recurring issue. Let's do a separate PR for it as a follow up.

**Review by deepthi — APPROVED** [review]

**Comment by nate-double-u** [comment]
Hi @mattlord, i'd be happy for you to push a commit -- i'm not going to be able to look at this till tomorrow, so there's still some time 🙂

**Comment by nate-double-u** [comment]
> Looks good! My only observation is that **pdfs folder** is placed right before v11.0. I expect the reverse to be the case- `older versioned docs` should come last on the list.

Thanks, I think I'll leave it as is for now. We can open a follow up if folks want to change it up.

**Comment by nate-double-u** [comment]
Thanks for all the help and feedback everyone!

**Pull request merged**
