### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Ayush9026**
## Description

This pull request solved this issue https://github.com/vitessio/website/issues/1743 added CONTRIBUTING.md file.This file will provide clear guidelines for new and existing contributors on how to contribute to the project. It will help streamline the contribution process and ensure that contributions align with the project's standards and practices.

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
Thank you

**Comment by Ayush9026** [comment]
Thank you @shlomi-noach sir.

**Comment by deepthi** [comment]
@Ayush9026 we already have a contributing page on the website at https://vitess.io/docs/contributing/ and a markdown file in the main repo which links to that page. It's not a good idea to add yet another file/place for this information. If you would like to improve the existing contribution page and add more content to it, we can review that, but this PR will need to be reverted.

**Comment by Ayush9026** [comment]
@deepthi mam, understood. I agree that adding another file isn't the best approach. I'll focus on improving the existing contribution page instead. I'll update the content there, and we can review those changes. I'll revert this PR. Thanks for the guidance.

**Pull request merged**
