### PR TITLE
chore: fix flaky search

### LINKED ISSUE #1204: Search returns "no result found" and some result when an incorrect value is searched
Screenshot 2022-10-27 at 16 22 07

### PR DESCRIPTION
**Pull request by thisisobate**
fixes #1204

### CODE REVIEW

**Review by mattlord — APPROVED** [review]
You may tire of the praise and gratitude but thank you! 🙂  All of this work is very much appreciated ❤️

**Comment by thisisobate** [comment]
@mattlord it seems the CI is acting up. I made some changes that work well on local but doesn't on netlify. How can we resolve issues like this? Maybe we need to clear some cache on Netlify?

**Comment by thisisobate** [comment]
seems like it's a cache problem; verified on local

**Comment by mattlord** [comment]
> seems like it's a cache problem; verified on local

I had checked during review and it worked as expected in the preview.

**Comment by thisisobate** [comment]
From what I can see on my end, it doesn't.
## Steps to Reproduce the Problem
1. Go to search and type "vitess"
2. once it loads results,press the delete key once to remove the 's' in vitess
3. notice how the "no result found" and actual result show same time

This PR fixes the issue so that only the "no results found" shows one time.

**Comment by thisisobate** [comment]
if you pull this branch and run on local, you'll see what I mean

**Comment by mattlord** [comment]
Ah, yes. I see that on the live site.

**Comment by thisisobate** [comment]
yep. I think we need to either clear the cache on Netlify or we ignore the cache on netlify

**Comment by thisisobate** [comment]
Since I don't have access to Netlify, can you help me clear the cache on your end?

**Comment by mattlord** [comment]
> Since I don't have access to Netlify, can you help me clear the cache on your end?

I didn't see anything obviously related in the UI. Any pointers? We can also move this discussion to Slack if you want.

**Comment by thisisobate** [comment]
sure...see you on slack!

**Pull request merged**
