### PR TITLE
Add initial docs for vstream

### LINKED ISSUE #252: Document VStream
Vstream replaces the update stream. It is not currently documented.

### PR DESCRIPTION
**Pull request by J0**
Fix #252

### CODE REVIEW

**Comment by J0** [comment]
Questions the uninformed reader should be able to answer after reading:

1. What is VStream?
2. Where is it located?
3. How is VStream used within Vitess
4. How can I modify Vstream for my own use(at a high level)
5. What is the similarity (if any) between VStream and the VStreamer

**Comment by J0** [comment]
Currently trying to get the image to render properly on the site but I just wanted to get an opinion on the content first.

**Comment by morgo** [comment]
LGTM

**Comment by morgo** [comment]
@J0 do you mind fixing the graphic? I think this is otherwise ready to merge.

**Comment by J0** [comment]
ok @morgo done.

**Review by morgo — APPROVED** [review]
LGTM

**Pull request merged**
