### PR TITLE
Chore: Show spinner during search

### LINKED ISSUE #1376: Update search UX
> @thisisobate I have a UX nit. Now that the index holds _all the content_ the search functionality has more work to do and there is lag between starting the search and providing the result. 
> 
> Let's have the search event handler **immediately display a spinner animation** so that as soon as the search starts, the end-user gets immediate feedback that a search is taking place. What do you think? Doable?

_Originally posted by @RobertKielty in https://github.com/vitessio/website/issues/1370#issuecomment-1408266921_

### PR DESCRIPTION
**Pull request by thisisobate**
Fixes #1376

### CODE REVIEW

**Comment by thisisobate** [comment]
cc: @RobertKielty

**Comment by RobertKielty** [comment]
I'll take a look soon.

**Comment by thisisobate** [comment]
cc: @deepthi

**Review by nate-double-u — APPROVED** [review]
This helps a lot, thanks @thisisobate

**Comment by RobertKielty** [comment]
Nice one, @thisisobate this is a good improvement. 

Nits, consider ... 

- left aligning the spinner to the left border of the search input box (quick way out would be to center the spinner in the results drop down)   
- including the text **Searching index ...**

**Comment by thisisobate** [comment]
@RobertKielty By design, input search texts are left aligned. So we can't really change that because it's expected behavior. 
I agree on centering the spinner; would be pushing an update soon.

**Review by deepthi — APPROVED** [review]
Looked at the preview. 👍

**Pull request merged**
