### PR TITLE
Fix broken url in docs

### PR DESCRIPTION
**Pull request by saintmalik**
Signed-off-by: Saintmalik 

## Summary

Easy navigation and easy reading for others

### CODE REVIEW

**Review by hallaroo — CHANGES_REQUESTED** [review]
This isn't how you'd fix this broken link, unfortunately, as the link is broken due to the page it was pointing to being removed [here](https://github.com/vitessio/website/issues/700). The ../ needs to remain the same.

Instead you need to add the following alias to the header of the .md of the new overview page [here](https://vitess.io/docs/reference/vreplication/vreplication/):

aliases: ['/docs/reference/features/vreplication/']

Once those two changes are made I can review again. Thank you!

**Comment by saintmalik** [comment]
Ohhh, didn't notice that, will push the fix now

**Comment by saintmalik** [comment]
> This isn't how you'd fix this broken link, unfortunately, as the link is broken due to the page it was pointing to being removed [here](https://github.com/vitessio/website/issues/700). The ../ needs to remain the same.
> 
> Instead you need to add the following alias to the header of the .md of the new overview page [here](https://vitess.io/docs/reference/vreplication/vreplication/):
> 
> aliases: ['/docs/reference/features/vreplication/']
> 
> Once those two changes are made I can review again. Thank you!

how do i add the aliases on the page

**Comment by hallaroo** [comment]
For sure!

You'll want to add it to the 'header' section of the /reference/vreplication/vreplication.md file like so:

```
---
title: Overview
description: VReplication features, design and options in a nutshell
weight: 2
aliases: ['/docs/reference/features/vreplication/']
---
```

**Comment by saintmalik** [comment]
> For sure!
> 
> You'll want to add it to the 'header' section of the /reference/vreplication/vreplication.md file like so:
> 
> ```
> ---
> title: Overview
> description: VReplication features, design and options in a nutshell
> weight: 2
> aliases: ['/docs/reference/features/vreplication/']
> ---
> ```

Done

**Review by hallaroo — APPROVED** [review]
Tested in the preview and that works perfectly. 

LGTM

**Pull request merged**
