### PR TITLE
Versioning prep work

### PR DESCRIPTION
**Pull request by nate-double-u**
Some prep work for PR #907 
Contributes to #625 

Moving `static/_redirects` -> `layouts/index.redirects`
Consolidating all redirects in new `layouts/index.redirects` file
Adding sample variable in new `layouts/index.redirects` file for #907 prep
Updating `config.toml`:
  * for use with new `layouts/index.redirects` file
  * with `[params.versions]` `latest`

### CODE REVIEW

**Comment by nate-double-u** [comment]
All redirect rules processed correctly:

Screen Shot 2021-12-20 at 2 57 04 PM

Deploy preview:
* https://deploy-preview-912--vitess.netlify.app/

## Redirect rules spot check
* https://deploy-preview-912--vitess.netlify.app/slack
* https://deploy-preview-912--vitess.netlify.app/user-guide/server-configuration
* https://deploy-preview-912--vitess.netlify.app/user-guide/vschema
* https://deploy-preview-912--vitess.netlify.app/getting-started
* https://deploy-preview-912--vitess.netlify.app/getting-started/local/

## Incorrectly working redirects

I'm not sure that these are working in the site currently. How are these supposed to work now?

```
/vitess/*   go-get=1 /go-import/vitess.html   200
/messages/* go-get=1 /go-import/messages.html 200
/operator/* go-get=1 /go-import/operator.html 200
```

For example: https://vitess.io/vitess/vitess.html 404s, but https://vitess.io/go-import/vitess.html loads.

**Comment by nate-double-u** [comment]
/hold

I rebased backwards 😓

**Comment by nate-double-u** [comment]
/unhold

Sorted rebase -- sorry about that.

**Comment by deepthi** [comment]
> ## Incorrectly working redirects
> I'm not sure that these are working in the site currently. How are these supposed to work now?
> 
> ```
> /vitess/*   go-get=1 /go-import/vitess.html   200
> /messages/* go-get=1 /go-import/messages.html 200
> /operator/* go-get=1 /go-import/operator.html 200
> ```

@derekperkins do you know how these work?

> 
> For example: https://vitess.io/vitess/vitess.html 404s, but https://vitess.io/go-import/vitess.html loads.

@nate-double-u the second URL loads a blank page for me (Safari on Mac)
In any case, I would not hold up this PR or the versioned docs PR on these redirects.

**Comment by nate-double-u** [comment]
> @nate-double-u the second URL loads a blank page for me (Safari on Mac)

That appears to be correct behavior for the second link (the second link is where the first should redirect to. I think there are some headers set on that page)

**Review by deepthi — APPROVED** [review]
Thank you!

**Comment by deepthi** [comment]
We need to open a separate issue for the redirects that aren't working.
```
/vitess/*   go-get=1 /go-import/vitess.html   200
/messages/* go-get=1 /go-import/messages.html 200
/operator/* go-get=1 /go-import/operator.html 200
```

**Comment by nate-double-u** [comment]
> We need to open a separate issue for the redirects that aren't working.

Followup issue: https://github.com/vitessio/website/issues/917

**Pull request merged**
