### PR TITLE
Chore: fix search overflowing view on mobile

### LINKED ISSUE #1413: Search not mobile friendly -- popup overflows view
- No popup appears after typing search text in the search input on mobile
- Possibly related? #1156

/cc @nate-double-u @thisisobate

### PR DESCRIPTION
**Pull request by thisisobate**
fixes #1413

### CODE REVIEW

**Comment by thisisobate** [comment]
cc: @nate-double-u @chalin @deepthi

**Review by nate-double-u — COMMENTED** [review]
image

Looks good from a visual standpoint. CSS isn't my strong point so I'll leave it to others to review the code. 

Tested using Safari on an iPhone SE running iOS version 16.3.1

**Review by chalin — COMMENTED** [review]
Thanks, that's a step in the right direction, so this could be merged, though there's still an issue with the content as illustrated by the following screenshot:

Vitessio-mobile-search-overflow

Notice the horizontal overflow.

**Comment by deepthi** [comment]
@thisisobate do you want to merge this as-is and fix the horizontal overflow in a different PR? Though it's probably more efficient to just pile that on to this one.

**Comment by nate-double-u** [comment]
Just a note, Uche is travelling and may take a few days to get back to this
🙂

**Comment by thisisobate** [comment]
@deepthi oh yes! I'm back now.
Taking a look at all the comments and pushing fixes where necessary.

**Comment by thisisobate** [comment]
cc: @deepthi

**Review by nate-double-u — APPROVED** [review]
/lgtm

Thanks @thisisobate

**Pull request merged**
