### PR TITLE
Docs: vttablet PITR via --restore-to-timestamp and --restore-to-position

### PR DESCRIPTION
**Pull request by shlomi-noach**
Documenting the changes in https://github.com/vitessio/vitess/pull/13964, and specifically these `vttablet` flags:

- `--restore-to-timestamp`
- `--restore-to-position`

Either of which, combined with `--restore_from_backup`, causes the tablet to start using a point-in-time recovery.

### Only merge once https://github.com/vitessio/vitess/pull/13964 is merged

### CODE REVIEW

**Review by ajm188 — COMMENTED** [review]
vttablet now also has auto-generated docs](https://github.com/vitessio/website/pull/1580), so you should also update those with (assuming you have your changes checked out in vitessio/vitess): `COBRADOCS_VERSION_PAIRS="HEAD:18.0" VITESS_DIR=/where/does/shlomi/keep/vitess make vttablet-docs` (alternatively, `make generated-docs` to do 'em all instead of just the one binary; same envvars apply)

**Comment by shlomi-noach** [comment]
Cool! This actually changed nothing, except for this line, which apparently leaks devs' home directories:

```
--config-path strings                                              Paths to search for config files in. (default [/Users/andrew/dev/vitess])
```

**Comment by ajm188** [comment]
> Cool! This actually changed nothing, except for this line, which apparently leaks devs' home directories:
> 
> ```
> --config-path strings                                              Paths to search for config files in. (default [/Users/andrew/dev/vitess])
> ```

yeah, we noticed this last night and @frouioui opened #1601 for it

**Comment by ajm188** [comment]
hmm, this should have updated https://vitess.io/docs/18.0/reference/programs/vttablet/#options with the added flags, was your `HEAD` maybe not on that branch?

**Comment by shlomi-noach** [comment]
>  was your HEAD maybe not on that branch?

It was, and I also ran `make build` to ensure the binaries were up to date...

**Comment by ajm188** [comment]
ahh, your PR is based 2 weeks ago, before the `vttablet` docgen stuff got added. if you merge to at least https://github.com/vitessio/vitess/commit/98c754a8fa068c7327fd05b7d83ac63da0cd80dd you should get it working

**Comment by shlomi-noach** [comment]
I've merged latest `main`, executed again, and still no dice. No change to docs other than that line I mentioned above.

**Comment by shlomi-noach** [comment]
Updated to reflect dashes, not underscores. Automation still does not change the `vttablet` docs.

**Comment by shlomi-noach** [comment]
Now that https://github.com/vitessio/vitess/pull/13964 is merged into `main` this works. I'm not sure why this wouldn't work when the branch was still unmerged?

**Comment by ajm188** [comment]
> I'm not sure why this wouldn't work when the branch was still unmerged?

It depends on what you used for `COBRADOC_VERSION_PAIRS`, and what state your local checkout was. If, for example, you did `HEAD:18.0`, and you had vitess checked out to some other branch that didn't have your changes, it wouldn't reflect in the docs. If instead you did `<your-vitess-branch-here>:18.0` then it would.

**Review by ajm188 — APPROVED** [review]

**Comment by shlomi-noach** [comment]
> It depends on what you used for COBRADOC_VERSION_PAIRS, and what state your local checkout was. If, for example, you did HEAD:18.0, and you had vitess checked out to some other branch that didn't have your changes, it wouldn't reflect in the docs. 


I did `HEAD:18.0` and my branch was checkout to the appropriate branch, and I made sure to run `make build`.

> If instead you did <your-vitess-branch-here>:18.0 then it would.

I did that as well, and made sure to run `make build`

**Comment by ajm188** [comment]
> I did `HEAD:18.0` and my branch was checkout to the appropriate branch, and I made sure to run `make build`.
> 
> 
> I did that as well, and made sure to run `make build`

weiiiiird!

the only guess i have (and it doesn't super matter since it seems to be working for you now) is maybe you started in the website dir prior to [this change](https://github.com/vitessio/website/pull/1583/files#diff-87407316b286eb799c2a61d064a0a56e98c993dc47701dd75637a4867c79fb04)? then if you had `HEAD` at your branch and `main` as the previous branch then every command after the first would have `git checkout -` send you back to `main` (and since vttablet is not first you would generate docs from main)

**Comment by shlomi-noach** [comment]
The website has been meanwhile frozen for `v18` RC1 release. Therefore, this PR was updated to apply the changes to both `18.0` and the new `19.0` paths.

**Pull request merged**
