### PR TITLE
VReplication FAQ: initial set

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
A few commonly occurring issues that cause questions to support have been documented. This is a very small set to start with. Aim is to keep adding to these often by looking up Slack questions and based on feedback from others.

A new hugo layout shortcode `expand` has been added to support collapsible sections, which are ideal for a FAQ.

Signed-off-by: Rohit Nayak <rohit@planetscale.com>

### CODE REVIEW

**Comment by rohit-nayak-ps** [comment]
For reference, FAQ link: https://deploy-preview-799--vitess.netlify.app/docs/reference/vreplication/faq/

**Review by hallaroo — APPROVED** [review]
LGTM - I just indented one additional line as it was weird that only line 10 needed to scroll in that expanded FAQ section.

Also - do you think we can use this expand shortcode for the main FAQs https://vitess.io/docs/faq/?

**Comment by shlomi-noach** [comment]
> Also - do you think we can use this expand shortcode for the main FAQs https://vitess.io/docs/faq/?

I think it makes more sense when:

- code snippets are involved, or:
- there's many questions.

I think https://vitess.io/docs/faq/ looks fine the way it is.

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps will be away for a while. I'm merging this PR on his behalf.

**Pull request merged**
