### PR TITLE
Update docs for ers

### PR DESCRIPTION
**Pull request by GuptaManan100**
This PR updates the docs for ERS reflecting the changes in vitessio/vitess#8492

### CODE REVIEW

**Comment by GuptaManan100** [comment]
This PR is not to be merged until release-12 docs have been saved. These changes have not gone into release-12

**Review by hallaroo — APPROVED** [review]
LGTM

**Comment by hallaroo** [comment]
> This PR is not to be merged until release-12 docs have been saved. These changes have not gone into release-12

I'll update here once I've made the v12 docs PDF.

**Comment by hallaroo** [comment]
> > This PR is not to be merged until release-12 docs have been saved. These changes have not gone into release-12
> 
> I'll update here once I've made the v12 docs PDF.

And I've created the v12 pdf of the docs: https://github.com/vitessio/website/pull/852, so whenever you want to merge that shouldn't be blocking any more. Thanks!

**Comment by GuptaManan100** [comment]
Alright! thankyou very much!

**Pull request merged**
