### PR TITLE
monthly broken link fixing

### PR DESCRIPTION
**Pull request by hallaroo**
Monthly check and fix for broken links on vitess.io/docs

### CODE REVIEW

**Review by askdba — COMMENTED** [review]
https://deploy-preview-657--vitess.netlify.app/blog/2015-10-06-cloud-native-mysql-sharding-with-vitess-and-kubernetes/ 
Links work but images are missing. 
Others LGTM

**Comment by hallaroo** [comment]
Good point - I have no idea where those images went so I think the best option will be to simply remove them. I'll get that update made a re-request a review.

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by askdba** [comment]
@rohit-nayak-ps beat me to it. For images probably they were external links. Thanks

**Comment by hallaroo** [comment]
Thank you both!!!!!

**Pull request merged**
