### PR TITLE
Document concurrent migrations

### LINKED ISSUE #890: Document OnlineDDL concurrent migrations
`design-docs/online-ddl/scheduler.md` details how the Online DDL scheduler works internally.

https://github.com/vitessio/vitess/pull/9192 (still unmerged at this time) makes significant changes to scheduling logic by allowing concurrent migrations (see also #9230).

Self assigning to document those changes.

### PR DESCRIPTION
**Pull request by shlomi-noach**
Fixes https://github.com/vitessio/website/issues/890

Documenting changes in https://github.com/vitessio/vitess/pull/9192, the introduction of concurrent migrations.

Since https://github.com/vitessio/vitess/pull/9192 is not merged yet, I'm marking this as a draft PR. Will make it ready to review once https://github.com/vitessio/vitess/pull/9192 is merged.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
OK weird, the preview does not show the `concurrent-migrations` page even though my local `hugo` run does. Screenshot of my local hugo run:

Screenshot from 2021-11-23 13-47-00
.

**Comment by shlomi-noach** [comment]
There we go: https://deploy-preview-891--vitess.netlify.app/docs/user-guides/schema-changes/concurrent-migrations/

**Comment by shlomi-noach** [comment]
https://github.com/vitessio/vitess/pull/9192 is now merged, and this PR is ready for review

**Comment by shlomi-noach** [comment]
https://github.com/vitessio/vitess/pull/9192 is now merged, and this PR is ready for review

**Review by askdba — APPROVED** [review]
LGTM

**Pull request merged**
