### PR TITLE
Docs: Backup/BackupShard --incremental-from-pos accepts backup name

### PR DESCRIPTION
**Pull request by shlomi-noach**
This PR documents the changes in https://github.com/vitessio/vitess/pull/14923, `--incremental-from-pos` accepting a backup name.

There is a lot of noise because of SHA signatures. The relevant changes are mostly in `content/en/docs/19.0/user-guides/operating-vitess/backup-and-restore/creating-a-backup.md` and otherwise in `vtctl` and `vtctldclient` docs.

### CODE REVIEW

**Comment by mattlord** [comment]
We only need to update the non-auto-generated pages here as the `vtctldclient` reference pages happen automatically based on the client binary output. I.e. we only need to update the user guide and vtctl[client] pages. Can you please remove the other changes so that it's easier to review?

**Comment by shlomi-noach** [comment]
> We only need to update the non-auto-generated pages here as the vtctldclient reference pages happen automatically based on the client binary output. I.e. we only need to update the user guide and vtctl[client] pages. 

That's what happens when I auto-generate the docs. I've been at it for many PRs now, I'm told this "just works" but clearly I didn't make all these changes manually...

**Comment by ajm188** [comment]
@mattlord see https://github.com/vitessio/website/issues/1602#issuecomment-1855882870

**Comment by shlomi-noach** [comment]
Looking back at my own comment I don't like how it reads. I'm sorry about that, it gives a wrong impression. At any case, please let me know how to proceed otherwise.

**Comment by mattlord** [comment]
> @mattlord see [#1602 (comment)](https://github.com/vitessio/website/issues/1602#issuecomment-1855882870)

I did see that but didn't realize that it was still broken. Sorry about that.

**Review by mattlord — APPROVED** [review]
This LGTM (although `vtctl` in the page's headers feels a bit off now -- we could say vtctld[client] now): https://deploy-preview-1662--vitess.netlify.app/docs/19.0/user-guides/operating-vitess/backup-and-restore/creating-a-backup/#create-an-incremental-backup-with-vtctl

And I approved the vitess PR so as long as we regenerate the docs based on the latest in the PR branch we'll be good. 

Thanks!

**Comment by shlomi-noach** [comment]
This branch is a mess. Replacing with a new PR.

**Pull request closed without merging**
