### PR TITLE
Add TxThrottler dry-run CLI flag to vttablet command line reference

### PR DESCRIPTION
**Pull request by ejortegau**
This PR adds docs for the new `--tx-throttler-dry-run` to the `vttablet` command reference. Related to https://github.com/vitessio/vitess/pull/13604

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
Looks good. Should be merged only after the code PR is merged.

**Comment by shlomi-noach** [comment]
@ejortegau can you please fix the merge conflict, introduced by https://github.com/vitessio/website/pull/1545?

**Comment by ejortegau** [comment]
Conflict fixed.

**Comment by ejortegau** [comment]
This CI run also seems to not start

**Comment by shlomi-noach** [comment]
OK maybe something with netlify. I'll follow up.

**Pull request merged**
