### PR TITLE
Add ant to brew installs on Mac OS contributing guide

### PR DESCRIPTION
**Pull request by BenMusch**
This dependency is required to install zookeeper locally

### CODE REVIEW

**Comment by morgo** [comment]
Thank you for your contribution!

Just so we are on the same page, the tutorial should not require zookeeper, provided that the bootstrap is run without Java:
```
BUILD_PYTHON=0 BUILD_JAVA=0 ./bootstrap.sh
```

The local example is also etcd-based, which is why this choice was made. In future of course, the default for `BUILD_JAVA` should be `0` so this step can be skipped.

Unless I am missing something here?

**Comment by BenMusch** [comment]
@morgo That's correct -- I was interpreting the doc more as "everything you need to run vitess locally on a mac" so when I hit the zookeeper roadblock I updated it here

Would there be a better place to document this?

**Comment by morgo** [comment]
My thoughts were:
The get-started and contribution guides benefit from being etcd based, because it's so much lighter on dependencies / is a fellow CNCF project.

Then there should be a User Guide for Switching the TOPO to zookeeper, and maybe another one for consul. It's the last item here on the user-guide improvements list: https://github.com/vitessio/website/issues/263

I think it is important to have guides to show how to switch it, because in many cases users will already have their favorite TOPO. Asking them to switch to another is never a compelling argument. It's just a balancing act with initial friction/simplicity.

What do you think?

**Comment by BenMusch** [comment]
Agree with that reasoning, thanks for the insight! Closing this PR as a result

**Pull request closed without merging**
