### PR TITLE
adding weight and readding monitoring doc

### PR DESCRIPTION
**Pull request by hallaroo**
Re-adding monitoring doc from https://vitess.io/docs/reference/features/two-phase-commit/#monitoring.

I removed reference to webpages that now 404.

### CODE REVIEW

**Comment by askdba** [comment]
We need to remove reference to google forum ```In the meantime, if you run into issues or have questions, please post on our forum.``` instead refer to Slack link or this pager at https://vitess.io/docs/faq/#what-are-the-key-slack-channels-to-join

**Review by askdba — COMMENTED** [review]
LGTM, @systay please review.

**Comment by hallaroo** [comment]
@systay - Would you possibly have a chance to review this over this week? It would be fantastic if you do. Thank you!

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Comment by hallaroo** [comment]
@rohit-nayak-ps - Thank you!!!!

**Pull request merged**
