### PR TITLE
Add docs for WORKLOAD_NAME directive

### PR DESCRIPTION
**Pull request by ejortegau**
This PR adds docs for the feature being added in https://github.com/vitessio/vitess/pull/12394

### CODE REVIEW

**Review by frouioui — APPROVED** [review]

**Review by harshit-gangal — APPROVED** [review]

**Comment by harshit-gangal** [comment]
you have to rebase or something to trigger CI again

**Comment by ejortegau** [comment]
> you have to rebase or something to trigger CI again

I just pushed an empty commit - nothing to rebase against as there are no changes in `prod` branch. Let's see if that is enough.

**Comment by ejortegau** [comment]
It looks like CI is still stuck - even after pushing empty commit. Not sure how to proceed here.

**Comment by harshit-gangal** [comment]
Closed against https://github.com/vitessio/website/pull/1412

**Pull request closed without merging**
