### PR TITLE
Added qoddi.com logo

### PR DESCRIPTION
**Pull request by qoddiapps**
Signed-off-by: Alexandre Gonzales President <alex@qoddi.com>

### CODE REVIEW

**Review by deepthi — COMMENTED** [review]
The DCO needs to be fixed (by adding a signoff to the commit)

**Comment by qoddiapps** [comment]
DCO added inside the initial commit, sorry about that!

**Review by askdba — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
> DCO added inside the initial commit, sorry about that!

Unfortunately the DCO check is still failing. Instructions for fixing are here https://github.com/vitessio/website/pull/908/checks?check_run_id=4503142175

Thank you for your patience with this, and for adding yourself to the website. Welcome to Vitess 😃

**Comment by askdba** [comment]
@qoddiapps it may be better to close this and do another PR. At least I do that when I fail on DCO.

**Comment by rsajwani** [comment]
closing this PR , as its being open for a long time with no progress...

**Pull request closed without merging**
