### PR TITLE
Docs: OnlineDDL cut-over backoff and force-cut-over

### PR DESCRIPTION
**Pull request by shlomi-noach**
Documenting the changes in https://github.com/vitessio/vitess/pull/14546:

- `ALTER VITESS_MIGRATION ... FORCE_CUTOVER ...`
- `--force-cut-over-after` strategy flag
- Cutover backoff
- How forced cut-over works

### CODE REVIEW

**Review by ajm188 — APPROVED** [review]
can you generate the `vtctldclient` docs for the new command as well?

**Comment by shlomi-noach** [comment]
> can you generate the vtctldclient docs for the new command as well?

Completely forgot how to do that 😬

**Comment by ajm188** [comment]
in your particular case (I _think_):

```
COBRA_DOC_VERSION_PAIRS=onlineddl-cutover-backoff:19.0 make vtctldclient-docs
```

edit: also you'll need to point it at your local vitess checkout https://github.com/vitessio/website/blob/prod/Makefile#L104

**Comment by shlomi-noach** [comment]
OK did that. That updated plenty CLI flags, but nothing related to the new command.

I feel like we've been in this situation before. I did run `make build` on my local path. I did point to the correct path:

```
COBRA_DOC_VERSION_PAIRS=onlineddl-cutover-backoff:19.0 VITESS_DIR=/Users/my-redacted-path make vttablet-docs
```

**Comment by ajm188** [comment]
> OK did that. That updated plenty CLI flags, but nothing related to the new command.
> 
> I feel like we've been in this situation before. I did run `make build` on my local path. I did point to the correct path:
> 
> ```
> COBRA_DOC_VERSION_PAIRS=onlineddl-cutover-backoff:19.0 VITESS_DIR=/Users/my-redacted-path make vttablet-docs
> ```

you need to make `vtctldclient-docs` as that's where the command is: https://github.com/vitessio/vitess/pull/14546/files#diff-13c32ab29d8892d009025725f22f4c9bdf7433141be13cd0ef8fe0615ccefb36

**Comment by shlomi-noach** [comment]
> you need to make vtctldclient-docs

Absolutely right! My mistake. Alas: did that, now over 450 new files changes -- none of which depicts the new command.

**Comment by shlomi-noach** [comment]
@ajm188 having merged https://github.com/vitessio/vitess/pull/14546, I tried again using `COBRA_DOC_VERSION_PAIRS=main:19.0` and that worked. It looks to me like a non-`main` branch name just doesn't work?

**Comment by shlomi-noach** [comment]
The newly added file is [`content/en/docs/19.0/reference/programs/vtctldclient/vtctldclient_OnlineDDL/vtctldclient_OnlineDDL_force-cutover.md`](https://github.com/vitessio/website/pull/1641/files#diff-5bc004bd32491c2f833623b45d805f96d0a13dff579f5562465590af5112b8a6)

I still have some extra ~465 files changed, but I guess that's fine as it's just the commit SHA?

Looking for your final approval before merging.

**Comment by shlomi-noach** [comment]
Not sure why versions `16.0`, `17.0`, `18.0` were at all affected here. Again, I think the script just doesn't work correctly with a non-`main` branch name. Please advise.

**Comment by ajm188** [comment]
two things:

1. the script definitely works with non-`main` branches last i used it (before i went on leave). you do need to make sure the branches (including those for the other versions you're generating) are up-to-date locally (`git fetch --all` should be enough)

2. i think the extra noise is because the [bot seems to have not been auto-generating docs](https://github.com/vitessio/vitess/pull/14733#issuecomment-1853943985), which i had working before i left. i am looking into why that is currently

**Review by ajm188 — APPROVED** [review]
that said, this is fine to merge!

**Comment by shlomi-noach** [comment]
@ajm188 Thank you for the inspection and clarification!

**Pull request merged**
