### PR TITLE
fix typo in docs/reference/vtctl.md

### PR DESCRIPTION
**Pull request by seeekr**

### CODE REVIEW

**Comment by skinnylatte** [comment]
@seeekr thank you for contributing! please fix the the DCO error in this PR.

**Comment by seeekr** [comment]
@skinnylatte done!

**Comment by skinnylatte** [comment]
@seeekr thank you for catching this!

**Comment by seeekr** [comment]
@skinnylatte happy to assist -- thanks for making an effort to produce and maintain documentation! Not an easy task, especially for a specialized tool like vitess where there's so much to know about it...

**Pull request merged**
