### PR TITLE
Vitess site versioning

### LINKED ISSUE #625: Add applicable Vitess version to manual pages / documentation
#### Feature Description

Vitess is currently changing at a fast pace so some parts of the written documentation are not backwards compatible or only apply to specific versions of Vitess.
It would be good if when writing/updating documentation, author could attach the Vitess version it applies to. A simple example is the MySQL docs where there is version selector ([https://dev.mysql.com/doc/refman/8.0/en/](https://dev.mysql.com/doc/refman/8.0/en/)). 

#### Use Case(s)

For example, currently, Vitess 8.0 gh-ost integration has specialized syntax while newer versions have @@ddl_strategy. The 8.0 GA version and the 'Managed, Online Schema Changes' man page are out of sync. One would have to check man page version history to find out about deprecated specialized syntax . This would probably cause some confusion to unaware users.

### PR DESCRIPTION
**Pull request by nate-double-u**
fixes https://github.com/vitessio/website/issues/625

- [x] Setup folder based versioning
  - [x] Only docs (blog, community, and other pages left un-versioned)
  - [x] Current +1 
    - [x] (with instructions on how to add more)
  - [x] Respects the current locales [en & zh]
  - [x] Redirects original `docs/` folder to `v12.0` version of page.
  - [ ] ~Versions drop-down on top nav~

This is a big PR, i apologize for that. Primarily it's big because I'm moving the current docs [en & zh] into their respective v13.0 folders (using `git mv` to keep the git history).

For v11.0, I've checked the release tags from the main vitess code site (https://github.com/vitessio/vitess/releases/tag/v11.0.1), and it looks like v11.0.1 was released on 2021-09-09, so I checked for the closest commit before that date on the website side, which looks to be commit [2b7994f](https://github.com/vitessio/website/tree/2b7994ff1681078e0c45a442d3ff908822b8e2f5) and have copied those docs [en & zh] into the new docs v11.0 folders.

For v12.0, i've checked the release tags from the main vitess code site (https://github.com/vitessio/vitess/releases/tag/v12.0.0), and have added the v12 docs from the Oct 26, 2021 commit [f619873](https://github.com/vitessio/website/commit/f619873796cf4af305a5f0482634c1d159811fb8)  and have copied those docs [en & zh] into the docs v12.0 folders.

### en
* https://deploy-preview-907--vitess.netlify.app/docs/
* https://deploy-preview-907--vitess.netlify.app/docs/13.0/ (note the sidebar)
* https://deploy-preview-907--vitess.netlify.app/docs/12.0/ (note the sidebar)
* https://deploy-preview-907--vitess.netlify.app/docs/11.0/ (note the sidebar)

#### redirect spot-checks
* https://deploy-preview-907--vitess.netlify.app/docs/contributing/build-on-centos/
* https://deploy-preview-907--vitess.netlify.app/docs/next/
* https://deploy-preview-907--vitess.netlify.app/docs/current/
* https://deploy-preview-907--vitess.netlify.app/docs/next/contributing/build-on-centos/
* https://deploy-preview-907--vitess.netlify.app/docs/current/contributing/build-on-centos/

### zh
* https://deploy-preview-907--vitess.netlify.app/zh/docs/
* https://deploy-preview-907--vitess.netlify.app/zh/docs/13.0/ (note the sidebar)
* https://deploy-preview-907--vitess.netlify.app/zh/docs/12.0/ (note the sidebar)
* https://deploy-preview-907--vitess.netlify.app/zh/docs/11.0/ (note the sidebar)

#### redirect spot-checks
* https://deploy-preview-907--vitess.netlify.app/zh/docs/get-started/local/
* https://deploy-preview-907--vitess.netlify.app/zh/docs/next/
* https://deploy-preview-907--vitess.netlify.app/zh/docs/current/
* https://deploy-preview-907--vitess.netlify.app/zh/docs/next/get-started/local/
* https://deploy-preview-907--vitess.netlify.app/zh/docs/current/get-started/local/

## Key files/folders for review
* config.toml 
* netlify.toml
* layouts/index.redirects
* `content/en/docs`
* `content/zh/docs`

### CODE REVIEW

**Comment by nate-double-u** [comment]
I hadn't realized quite how much the built in hugo side bar would do for us. I think that this PR as is covers all the functional goals we set already.~; however, I still need to set up redirects so that anyone with bookmarks would aromatically get redirected to the v12.0 version of the page when they visit.~ (Redirects are in.)

I have made some changes to the [config.toml](https://github.com/vitessio/website/pull/907/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77) file in preparation for a versions drop-down in the top nav (like on [etcd.io](https://etcd.io/docs/v3.5/) or [cni.dev](https://www.cni.dev/plugins/current/)), but those can be easily picked out if we don't want or need a drop-down menu (please let me know your preference)

**Comment by nate-double-u** [comment]
/cc @deepthi @doeg @shlomi-noach 

Question: is what I grabbed for v11.0 appropriate?

**Comment by deepthi** [comment]
Wow, this is huge!

> Question: is what I grabbed for v11.0 appropriate?

I think it should instead be close to the 11.0 GA date. Once GA went out we would have started adding 12.0 in-progress docs to the website.

I have a few questions/comments of my own:
* The docs that we have on the website are not strictly 12.0, they are post 12.0 and surely have some content that isn't correct for 12.0. We should pick an approximate commit and copy the files over.
* What happens when we do 13.0? How do we add a new version?
* Ideally we would have a folder called main along with the last 2 releases, and when we do a release (or the first release candidate aka RC1), we simply rename that to the new release and start a new folder called main for WIP, but I'm not certain whether we would want to hide that until we are ready to release.

**Comment by nate-double-u** [comment]
> Wow, this is huge!

Ya, I'm not sure it can be smaller either, it's just a function of how many docs need to be duplicated and moved. I'll make a better note of any configs that need to be reviewed.

> > Question: is what I grabbed for v11.0 appropriate?
> 
> I think it should instead be close to the 11.0 GA date. Once GA went out we would have started adding 12.0 in-progress docs to the website.

OK, I can make that change. In future, we'll need to write up a release strategy for docs as a part of the Vitess main release process.
 
> I have a few questions/comments of my own:
> 
>     * The docs that we have on the website are not strictly 12.0, they are post 12.0 and surely have some content that isn't correct for 12.0. We should pick an approximate commit and copy the files over.

I'd suggest including anything in the 12.0 folder that is for any minor or patch version of 12.x -- and treat 12.x as _current_. 
 
>     * What happens when we do 13.0? How do we add a new version?

I'll write this up in the README, but essentially, when it's time for a v13, I recommend doing a `git mv` of v12 to v13 (to keep the file history), then making a copy of that new v13 back to v12 as the archive. I'm not sure of any way to keep the git history for both sets of files yet. Happy for suggestions from the wider community for a better way to deal with this.

That said, other projects have done it differently, incorporating a "next" and a "current" version, that are maintained somewhat separately, but I'm not a fan of that per se. I prefer keeping content in folders named after their versions, so in this case v12 would be the _current_, and a v13 would be _next_.
 
>     * Ideally we would have a folder called main along with the last 2 releases, and when we do a release (or the first release candidate aka RC1), we simply rename that to the new release and start a new folder called main for WIP, but I'm not certain whether we would want to hide that until we are ready to release.

As per my comment above, I'd suggest staying away from naming folders anything other than their version. I'd suggest instead creating a redirect that could be updated per release (for instance `/docs/next -> /docs/v13.0` and `/docs/current -> /docs/v12.0`, plus localized versions).

**Comment by deepthi** [comment]
> I recommend doing a git mv of v12 to v13 (to keep the file history), then making a copy of that new v13 back to v12 as the archive.

I don't think this is workable. We have lots of work happening on main in the source code repo, and people will be writing docs along with the code. We need a way to stage them and then release them as the next version (v13 for now).
The v12 version of the docs should be essentially frozen unless we do a patch release with bug fixes that require docs updates.

**Comment by nate-double-u** [comment]
> > I recommend doing a git mv of v12 to v13 (to keep the file history), then making a copy of that new v13 back to v12 as the archive.
> 
> I don't think this is workable. We have lots of work happening on main in the source code repo, and people will be writing docs along with the code. We need a way to stage them and then release them as the next version (v13 for now). The v12 version of the docs should be essentially frozen unless we do a patch release with bug fixes that require docs updates.

You could do that with release branches -- then merge them into prod on release day, at which point you can create a v14 branch (or whichever patch branch you need).

That's similar to how the Kubernetes project manages it, but the release branches have to be periodically rebased on main as that is where most error correction and non-release related re-organization goes (prod in this case).

[edit]
Regardless, a copy will need to be made when starting a new version. maybe not a `git mv` in this case, but the previous version is going to need to be the base for a new version.

**Comment by shlomi-noach** [comment]
> Question: is what I grabbed for v11.0 appropriate?

So right now it's hard for me to verify that; looking at some docs I "own", this looks correct.

For 12.0 the docs are incorrect, and as @deepthi suggests, reflect `main` branch. I know for sure about some docs that shouldn't be in `12.0`.

I'm thinking: shall we just move forward instead of backwards? I think we can make the effort to select the `12.0` appropriate docs; and then let's figure the best way to move forward to `13` and skip `11`?

My thoughts on how we'd version next releases: couple that with git flow:

- in the current preview, I only see `11.0` and `12.0`. But, In my opinion, we should have `11.0`, `12.0` and `main`, or "current".
- when we freeze a version, we will copy_paste "current" into the next version, be it `13.0` for example
- we always add to "current"
- we sometimes backport to previous versions

WDYT?

**Comment by nate-double-u** [comment]
The (relevant) folder structure of this PR is currently as follows:
```
content
├── en
│   └── docs
│       ├── 11.0
│       │   ├── _index.md
│       ├── 12.0
│       │   ├── _index.md
│       └── _index.md
└── zh
    └── docs
        ├── 11.0
        │   ├── _index.md
        ├── 12.0
        │   ├── _index.md
        └── _index.md
```

What I'm suggesting is that the folder structure always reflects the version; each of the `_index.md` files has a header section, which can change what is shown on the site, these are what should change from version to version.

```
---
title: v12.0
description: Everything you need to know about the world's most scalable open-source MySQL platform
notoc: true
cascade:
  version: v12.0
weight: 1000
---
```

Screen Shot 2021-12-15 at 9 27 02 AM

Screen Shot 2021-12-15 at 9 28 34 AM

```
---
title: Current
description: Everything you need to know about the world's most scalable open-source MySQL platform
notoc: true
cascade:
  version: v12.0
weight: 1000
---
```

Screen Shot 2021-12-15 at 9 27 36 AM

Screen Shot 2021-12-15 at 9 28 22 AM


On other sites, the redirect system is a bit different, and allows for variables. See [etcdio/website/layouts/index.redirects](https://github.com/etcd-io/website/blob/fb7f47d1e750706d550a08f42c272b5660222da4/layouts/index.redirects#L1-L3 
)

```
{{ $latest := site.Params.versions.latest }}
/docs/latest     /docs/{{ $latest }}/
/docs/latest/*     /docs/{{ $latest }}/:splat
```

This snippet pulls `{{ $latest := site.Params.versions.latest }}` from the [`config.toml` file](https://github.com/nate-double-u/vitessio-website/blob/b84b5d09469cb85cc40a62a9c2a4f251ac4e82e3/config.toml#L17-L18), which allows for a current or latest url to be updated during a release as well. The style of redirects that is currently being used on this site doesn't support these variables, so if we want to go this direction, we'll need to change that up too--but it works very well over on etcd.io and [grpc.io](https://github.com/grpc/grpc.io/blob/main/layouts/index.redirects).

**Comment by nate-double-u** [comment]
> > Question: is what I grabbed for v11.0 appropriate?
> 
> So right now it's hard for me to verify that; looking at some docs I "own", this looks correct.
> 
> For 12.0 the docs are incorrect, and as @deepthi suggests, reflect `main` branch. I know for sure about some docs that shouldn't be in `12.0`.
> 
> I'm thinking: shall we just move forward instead of backwards? I think we can make the effort to select the `12.0` appropriate docs; and then let's figure the best way to move forward to `13` and skip `11`?

I'm happy to drop `v11.0` and add a `v13.0`.

I think that `v12.0` and `v13.0` would be identical to begin -- this is unsurprising though since the most recent release of a v12 was yesterday (https://github.com/vitessio/vitess/releases/tag/v12.0.1). I'm not familiar enough with the Vitess content to parse the differences between v12 and v13, so I suggest that I build out the infrastructure for versioning, and after the website maintainers will need to go through and remove any incorrect info from v12.

**Comment by deepthi** [comment]
> I'm happy to drop v11.0 and add a v13.0.

@nate-double-u since you have already done the work for v11.0 let us not drop it. Technically we should provide docs for all supported releases, but I will be happy for us to start with v11.0 & v12.0 and build from there.
In the end state we will be maintaining docs for as many releases as we officially support, which is the last 3 major versions. So we would eventually add v13.0, but we would not drop v11.0 until we get to v14.0.

> I think that v12.0 and v13.0 would be identical to begin -- this is not unsurprising though since the most recent release of a v12 was yesterday (https://github.com/vitessio/vitess/releases/tag/v12.0.1). 

Yes v12.0 and v13.0 would be identical _at the point when we created v12.0_. That was back in October, so `prod` right now has a whole bunch of other stuff that didn't go into v12.0. v12.0.1 being a patch release made only minor changes to v12.0 and did not add any new features. Once we have a base for v12.0 it will be easy for any of the maintainers to then add the delta from v12.0.1 to it.
The way to determine a base commit for v12.0 would be to go back to the release date, which was Oct 26, 2021. If you could grab the closest commit on `prod` for that day, we should be good.

Re @shlomi-noach's comment:
> in the current preview, I only see 11.0 and 12.0. But, In my opinion, we should have 11.0, 12.0 and main, or "current".

Because we have so far had only one "version" of docs, it was by definition meant to be in sync with the `main` branch of the source repo. When we go to versioned docs, we should probably release the versioned docs for a new release at the same time that we release binaries. We can label them `beta` or `RC1` along with the `RC1` release too. I like the idea of using a branch to keep adding the docs and then doing a PR on prod to "release" them.
What this means is that we will start with v11.0 and v12.0 and copy over the current state of `prod` to `v13.0` or some such branch and they will disappear from the website at that point.
At least this is how other projects seem to do it. k8s.io and etcd.io have no "in-progress" or "current" docs, only docs for actually released versions.

**Comment by nate-double-u** [comment]
Should there be 2 separate sets of variables (in `config.toml` and in `layouts/index.redirects`), one for `en` and one for `zh`?

#### `config.toml`
```
[params.versions]
current = "12.0"
next = "13.0"
```

#### `layouts/index.redirects`
```
{{ $current := site.Params.versions.current }}
{{ $next := site.Params.versions.next }}

/docs/current                             /docs/{{ $current }}/
/docs/current/*                           /docs/{{ $current }}/:splat
/docs/next                                /docs/{{ $next }}/
/docs/next/*                              /docs/{{ $next }}/:splat

/zh/docs/current                          /zh/docs/{{ $current }}/
/zh/docs/current/*                        /zh/docs/{{ $current }}/:splat
/zh/docs/next                             /zh/docs/{{ $next }}/
/zh/docs/next/*                           /zh/docs/{{ $next }}/:splat
```

**Comment by deepthi** [comment]
@nate-double-u if we go ahead and create a release-13.0 branch with the current state on `prod` and you resolve the conflicts, we should be able to merge this. WDYT?

**Comment by nate-double-u** [comment]
I've just rebased onto prod, no conflicts remain 🙂

**Comment by deepthi** [comment]
> @nate-double-u if we go ahead and create a release-13.0 branch with the current state on `prod` and you resolve the conflicts, we should be able to merge this. WDYT?

Based on chat, we don't need this, we already have a v13.0 folder.

**Review by deepthi — APPROVED** [review]
It is not possible to review this one file at a time :)
The main menu looks good. The only thing we might change is 
v13.0 (Upcoming, next docs) -> v13.0 (Under construction, upcoming release)
AND
v12.0 (Current docs) -> v12.0 (Latest release)

**Comment by nate-double-u** [comment]
> It is not possible to review this one file at a time :) 

Unfortunately no. We'll likely need to go through and open follow up issues/PRs to fine tune where changes have landed (there are probably some things in v13.0 that should be in v12.0 and vice versa ) Unfortunately I'm not well versed enough in the docs here to be able to do that work. This is just a framework/structural update to start the versioning process.

> The main menu looks good. The only thing we might change is v13.0 (Upcoming, next docs) -> v13.0 (Under construction, upcoming release) AND v12.0 (Current docs) -> v12.0 (Latest release)

I've made these changes.

**Comment by deepthi** [comment]
Thank you @nate-double-u for getting this done. This has been a long-standing request.

**Comment by nate-double-u** [comment]
Happy to help!
And thanks for all the feedback 🙂

**Comment by mattlord** [comment]
THANK YOU, @nate-double-u ! ❤️ ❤️ ❤️ This is going to be so much better for everyone.

**Comment by mattlord** [comment]
@nate-double-u do you know of a relatively nice/easy way to accomplish this? https://github.com/vitessio/website/issues/921#issuecomment-1000924556

**Comment by nate-double-u** [comment]
> @nate-double-u do you know of a relatively nice/easy way to accomplish this? [#921 (comment)](https://github.com/vitessio/website/issues/921#issuecomment-1000924556)

Yes :)
See https://github.com/vitessio/website/pull/922

**Comment by shlomi-noach** [comment]
I wanted to circle back and say how good the docs are organized now version-wise. Well done!

**Pull request merged**
