### PR TITLE
Removing all reference to schema swap, mentioning SBR deprecation

### PR DESCRIPTION
**Pull request by skinnylatte**
WIP

Signed-off-by: Adrianna Tan <skinnylatte@gmail.com>

### CODE REVIEW

**Comment by skinnylatte** [comment]
@derekperkins have a look at: https://deploy-preview-174--vitess.netlify.com/docs/reference/vitess-replication/

I have also removed the schema swap doc

I plan to write a blog post about SBR deprecation.

Can you have a look at this PR (that is still WIP) and see what else I might have missed?

**Comment by skinnylatte** [comment]
on hold.

**Comment by indera-shsp** [comment]
is there a blog post about `SBR deprecation`?

**Comment by sougou** [comment]
Only this issue https://github.com/vitessio/vitess/issues/4593

**Pull request closed without merging**
