### PR TITLE
updating video container is-video

### PR DESCRIPTION
**Pull request by nate-double-u**
contributes to https://github.com/vitessio/website/issues/1763

updates video container `is-video` so it doesn't overflow when the window is resized.

### CODE REVIEW

**Comment by deepthi** [comment]
I looked at the preview. While it doesn't overflow any more, it does get cut-off on both left and right. Is there a way to get the container resized on mobile (to be smaller) so that we avoid this?

**Comment by nate-double-u** [comment]
interesting, i see that now too. I think it's just the title-card that doesn't resize correctly, the video still plays right.

I'll see what I can do.

**Review by chalin — COMMENTED** [review]
You'll want to drop the semicolons, btw.

**Comment by chalin** [comment]
@nate-double-u - is `bulma` due for an upgrade? Might that upgrade resolve the issue this PR is trying to solve?

**Comment by nate-double-u** [comment]
I tried updating Bulma locally (the site is only a dot version behind), and it didn't help. I'm not sure why the title card isn't scaling with the rest of the video, but the video behaves more correctly now.

That is to say in my testing it's only the title card that gets cut off, not the video. (Please correct me if I'm wrong here, I've admittedly only tested on Firefox and mobile)

**Comment by deepthi** [comment]
> I tried updating Bulma locally (the site is only a dot version behind), and it didn't help. I'm not sure why the title card isn't scaling with the rest of the video, but the video behaves more correctly now.
> 
> That is to say in my testing it's only the title card that gets cut off, not the video. (Please correct me if I'm wrong here, I've admittedly only tested on Firefox and mobile)

That is also what I'm seeing on iOS/Safari. It is at least better than before, if we want to call this "good enough for now".

IMG_9224

**Comment by deepthi** [comment]
@nate-double-u if you want to merge this, you will need to remove the semi-colons. I can approve after that.

**Comment by nate-double-u** [comment]
> @nate-double-u if you want to merge this, you will need to remove the semi-colons. I can approve after that.

Removed

**Review by deepthi — APPROVED** [review]

**Pull request merged**
