### PR TITLE
content/en/docs/18.0: rework vtbackup DurationByPhase into binary valued Phase

### PR DESCRIPTION
**Pull request by maxenglander**
Accompanies:
 
 * https://github.com/vitessio/vitess/pull/12973

### CODE REVIEW

**Review by deepthi — APPROVED** [review]
We'll wait to merge this until the linked code PR is merged.

**Review by deepthi — DISMISSED** [review]
@maxenglander since this isn't going into v17, can you move the changes to v18 of the docs?

**Comment by maxenglander** [comment]
Thanks @deepthi I've updated this PR as well as the changelog in https://github.com/vitessio/vitess/pull/12973

**Review by shlomi-noach — APPROVED** [review]

**Comment by shlomi-noach** [comment]
Requested changes were made. Merging.

**Pull request merged**
