### PR TITLE
translate blog schema-tracking

### PR DESCRIPTION
**Pull request by potterhe**
this pr translate blog schema-tracking to zh

### CODE REVIEW

**Comment by mattlord** [comment]
Thanks, @potterhe ! I've added our two native speakers, @Verolop and @frouioui, as reviewers. ❤️

**Comment by deepthi** [comment]
@potterhe can you fix the DCO? You will need to amend your commit with `--signoff` and `git push --force` or `git push --force-with-lease`.

**Comment by potterhe** [comment]
@deepthi done

**Review by Verolop — APPROVED** [review]
lgtm!

**Review by frouioui — APPROVED** [review]

**Pull request merged**
