### PR TITLE
Design docs: the OnlineDDL scheduler

### PR DESCRIPTION
**Pull request by shlomi-noach**
A design doc that explains how the OnlineDDL scheduler works, what's the scheduling logic, what the state machine looks like, how migrations are executed, etc.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Preview: https://deploy-preview-802--vitess.netlify.app/docs/design-docs/online-ddl/scheduler/

**Review by rohit-nayak-ps — APPROVED** [review]
Very nice. LGTM

**Comment by rohit-nayak-ps** [comment]
@shlomi-noach, updated the doc with some grammar issues etc as I was reading it. PTAL if you agree or fix otherwise.

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps looks great, thank you!

**Pull request merged**
