### PR TITLE
Fix some typos in documents under content/en/docs

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

### CODE REVIEW

**Review by hallaroo — APPROVED** [review]
Thanks for catching these!

**Comment by askdba** [comment]
@hs0210 can you fix conflicts so I can merge this?

**Comment by hallaroo** [comment]
@askdba - I had one of those typo's fixed in one of my PR's: https://github.com/vitessio/website/pull/850. I'm working on fixing now and then I can merge the two of them.

**Comment by hs0210** [comment]
@askdba thanks, done, PTAL.

**Pull request merged**
