### PR TITLE
Why write a new planner [Blog] 

### PR DESCRIPTION
**Pull request by askdba**
Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>

### CODE REVIEW

**Comment by askdba** [comment]
Do NOT merge until 11/2/2021

**Review by askdba — COMMENTED** [review]
LGTM

**Comment by derekperkins** [comment]
> the new planner takes about double the time that the old planner took to plan queries

I'd be interested to know what the scale is. 1ms -> 2ms?

**Comment by systay** [comment]
> I'd be interested to know what the scale is. 1ms -> 2ms?

You can check https://benchmark.vitess.io/microbench and search for the `BenchmarkPlanner*` tests. There you can compare two tests on the same query files, but with different planners. For example:

BenchmarkPlanner/aggr_cases.txt-gen4-56 is taking 6.31 ms to plan all the queries in [aggr_cases.txt](https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/testdata/aggr_cases.txt). 
The V3 planner is doing it in 3.46 ms.

**Review by systay — APPROVED** [review]

**Pull request merged**
