### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by Ayush9026**
This PR solves issue https://github.com/vitessio/website/issues/1742 by updating the README.md file by adding dedicated sections for Community and Contributing. These sections are crucial for providing information to new contributors and fostering a collaborative environment within our project.

### CODE REVIEW

**Comment by deepthi** [comment]
I'm not sure what open source philosophy or guidelines you are trying to implement here.
What we have:
vitess.io website with a contributing page
vitessio/vitess is the main code repo with a README for contributing to the project.

As it stands, the README for the website is clearly intended as guidance for developers on how to build the website. What is the rationale for adding the new sections?

**Comment by Ayush9026** [comment]
Thank you for your feedback, @deepthi mam.

Sorry, ma'am, for this oversight. The rationale for adding the Community and Contributing sections to the README.md is to enhance accessibility for new contributors. Although we have a contributing page on vitess.io, having this information in the README.md ensures it’s immediately visible and reduces friction for newcomers.

Many successful open-source projects, like Kubernetes and TensorFlow, follow a similar approach by including community and contributing sections directly in their README.md files

Again, sorry for the mistake. I hope this clarifies the intention behind the changes.

**Comment by deepthi** [comment]
The main repository for vitess is vitessio/vitess. There's a README in that repo along with many other markdown files - CONTRIBUTING / GOVERNANCE etc.
I expect people will go there first and that is where things need to live.
I don't understand why these things need to be added in the README file of the **website** repository.
I have looked at kubernetes/kubernetes, kubernetes/website and kubernetes/community repos and I don't see that we necessarily need to add what you are proposing into the website repo.

**Comment by deepthi** [comment]
We won't accept this PR in its current form.

**Pull request closed without merging**
