### PR TITLE
Document using vindex functions

### PR DESCRIPTION
**Pull request by bolt-leandro**
https://vitess.slack.com/archives/C0PQY0PTK/p1621349717006600

### CODE REVIEW

**Comment by deepthi** [comment]
@bolt-leandro can you fix the DCO?

**Comment by mattlord** [comment]
Hey, @bolt-leandro ! Nice to "see" you again. 🙂 We recently added `IN()` clause support as well in https://github.com/vitessio/vitess/pull/9426. Do you mind showing an example of that? I can also add it if you prefer.

Thank you for the great contribution! Not enough people know about this convenient tool.

**Comment by mattlord** [comment]
Hi @bolt-leandro,

Just checking in on this. Can I help to get this over the line, or would you rather I create a new PR for it?

Thanks again!

**Comment by mattlord** [comment]
I suspect the git handle and associated email address was an employer one that's no longer in use so I am closing this and moving the work here: https://github.com/vitessio/website/pull/964

**Comment by bolt-leandro** [comment]
Hi @mattlord , good to see you :) 
For some reason I only got notified of this issue being closed (previous requested never reached me).
I see you already moved work to https://github.com/vitessio/website/pull/964 which is fine by me. Thanks for that!

**Pull request closed without merging**
