### PR TITLE
Vitess OnlineDDL no longer experimental

### PR DESCRIPTION
**Pull request by shlomi-noach**
We consider Vitess's Online DDL to be production grade. This includein particular includes `vitess` strategy migrations, based on VReplication.

This PR updates the docs to remove "experimental" notes, and moreover indicate that Online DDL is the preferred way of running schema migrations in Vitess.

### CODE REVIEW

**Review by rohit-nayak-ps — APPROVED** [review]
lgtm

**Review by deepthi — APPROVED** [review]
Are we intentional about marking pt-osc as stable too?

**Comment by shlomi-noach** [comment]
@deepthi good question about `pt-osc`. I don't have a good answer as I don't have any information about usage, I'm good to keep it as experimental.

**Comment by shlomi-noach** [comment]
The docs now clarify `pt-osc` is experimental. If anyone is wondering, this is because we have not had any feedback from the community with regard `pt-osc` use in `vitess` online schema changes.

**Pull request merged**
