### PR TITLE
Initial set of VReplication design docs

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**

### CODE REVIEW

**Review by shlomi-noach — COMMENTED** [review]
This is awesome! I will also add some docs to this PR if that's OK:

- vreplication unique key/primary key requirements&limitations
- character set support

Possibly a couple docs specific to OnlineDDL as well

**Comment by rohit-nayak-ps** [comment]
> This is awesome! I will also add some docs to this PR if that's OK:
> 
> * vreplication unique key/primary key requirements&limitations
> * character set support
> 
> Possibly a couple docs specific to OnlineDDL as well

Absolutely. I still need to add more stuff to the cutover doc.

**Comment by shlomi-noach** [comment]
Added documentation page to explain how vreplication utilizes keys on source and target tables. At this time this is mostly requirements/limitations with many examples, and I want to also add a short internal implementation clause. See https://deploy-preview-792--vitess.netlify.app/docs/design-docs/vreplication/keys/

**Comment by shlomi-noach** [comment]
Added documentation for character set support and configuration: https://deploy-preview-792--vitess.netlify.app/docs/design-docs/vreplication/character-sets/

**Comment by shlomi-noach** [comment]
Let's get these shipped in the meantime. More to come. cc @deepthi

**Comment by shlomi-noach** [comment]
@hallaroo just wondering if you have a specific markdown linter that you're using to fix formatting?

**Comment by hallaroo** [comment]
@shlomi-noach - I don't ... I didn't even know that was a thing until I googled it 😳 . I've just been adjusting by hand what I know pandoc (the tool I use to PDF the docs) will not parse correctly.

I may now look into one (if you have suggestions that would also be appreciated).

**Comment by shlomi-noach** [comment]
Haha I was just wondering... I don't have suggestions though I did notice VSCode has a Markdown linter plugin, which I haven't tried yet... :laughing:

**Comment by hallaroo** [comment]
I should take a look at some before the next time I convert the .md's to a pdf (as it takes way too long to manually scroll the 100's of pages of pdf). Thank you!

**Review by deepthi — APPROVED** [review]

**Pull request merged**
