### PR TITLE
Online DDL: revertible migrations, declarative migrations, SQL commands

### PR DESCRIPTION
**Pull request by shlomi-noach**
Tracking issue: https://github.com/vitessio/vitess/issues/6926

This PR doucments changes from the following PRs:

- https://github.com/vitessio/vitess/pull/7478
- https://github.com/vitessio/vitess/pull/7638
- https://github.com/vitessio/vitess/pull/7656
- https://github.com/vitessio/vitess/pull/7663
- https://github.com/vitessio/vitess/pull/7694
- https://github.com/vitessio/vitess/pull/7725

It's a major refactor of the Online DDL documentation, offering new page and structuring.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
All of the relevant code changes have been merged, and so this doc update should be reviewed and merged as well

**Comment by shlomi-noach** [comment]
This needs to merged for v10 cc @askdba

**Review by askdba — COMMENTED** [review]
Can we remove references to Aurora/RDS as they aren't the best practice to be used with Vitess.

**Comment by shlomi-noach** [comment]
> Can we remove references to Aurora/RDS as they aren't the best practice to be used with Vitess.

Removed!

**Review by askdba — APPROVED** [review]
Thanks, lgtm.

**Pull request merged**
